services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL:
        NEXT_PUBLIC_CLIENT_ID:
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: production
    restart: unless-stopped
