---
name: Build and Push Container Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.14.0
        with:
          context: .
          build-args: |
            UID=${{ secrets.APP_USER_UID }}
            GID=${{ secrets.APP_USER_GID }}
            NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_CLIENT_ID=${{ secrets.NEXT_PUBLIC_CLIENT_ID }}
            NEXT_PUBLIC_GTM_ID=${{ secrets.NEXT_PUBLIC_GTM_ID }}
          push: true
          tags: ${{ secrets.CONTAINER_IMAGE_REPO }}/session-portal-frontend:${{ github.sha }}, ${{ secrets.CONTAINER_IMAGE_REPO }}/session-portal-frontend:latest
